### PR TITLE
Fix bug with full stack trace missing when using unity interception

### PR DESCRIPTION
**Pull request by istagir**

### CODE REVIEW

**Comment by istagir** [comment]
Recreated in https://github.com/unitycontainer/unity/pull/92

**Comment by ENikS** [comment]
I still need to understand what are you fixing. Could you include test implementations to demonstrate the issue?

**Comment by ENikS** [comment]
Excellent!

**Comment by ENikS** [comment]
All is well but I am not sure about #if-#else statements. Is there any way of doing it without conditional compiling? After all, Netstandard 1.0 is the main target, not the .NET 4.5

**Comment by istagir** [comment]
> All is well but I am not sure about #if-#else statements. Is there any way of doing it without conditional compiling? After all, Netstandard 1.0 is the main target, not the .NET 4.5 

Yea I have an idea about this. I'll try to implement it.

**Comment by ENikS** [comment]
Thank you for your help!

**Comment by ENikS** [comment]
Perhaps you would like to help with other issues? 
There are few more related to Interception for example...

**Comment by istagir** [comment]
Why not? I can help with some not difficult issues.
But it can be slowly, because i have not a lot of time.

**Comment by ENikS** [comment]
We are not rushing anywhere, take your time :)

**Pull request merged**
