### PR TITLE
Fixed method injection with the same method but different parameters

### PR DESCRIPTION
**Pull request by Eragra3**
Old unity could call method injection multiple times with exactly the same method, talking about Unity 3.x.
This got broken at some stage, one test was changed to fit new behavior, but I'm not sure if that was intentional.
I can see `Configuration` package test case changed in commit `b54e27f6`.

Test `When_ConfigurationContainerForMethodInjection.Then_FirstOverloadCalledTwice` was changed to suddenly expect only one method to be called.

Following code would call `CallMe` method twice with old unity, and only once (first occurence) with new one:
```xml
<register type="ObjectWithOverloads" name="callFirstOverloadTwice">
  <method name="CallMe">
    <param name="param" type="int" value="17" />
  </method>
  <method name="CallMe">
    <param name="param" type="int" value="35" />
  </method>
</register>
```

If the change was not intentional, I would like to bring back old behavior - it's blocking Unity upgrade in our company, and we are on ancient version `3.something`.

Included changes:
- `Unity.Abstractions` - fixed hash code generation for `InjectionMethod`
- `Unity.Configuration` - fixed related test case
- `Unity.Container` - bonus fix, props file seems to be missing chevron

**I've never worked with GIT submodules on GitHub, do I have to create PRs for each package separately?**

### CODE REVIEW

**Comment by Eragra3** [comment]
Well I guess I have to go one by one, also merge to `release/5.11` if I want to patch `5.x` version.

I would like to get green light from project owners first though.

**Comment by ENikS** [comment]
This behavior is by design. Calling same method multiple times is incorrect behavior and was deliberately fixed. Now you are trying to reintroduce that bug again.

**Comment by Eragra3** [comment]
Well, it doesn't seem a lot like a bug to me, method injection worked like initialization. So you could create a method that adds something (could be also injected).

Consider something like chain of responsibility, you could set up that chain by calling injection method multiple times and injecting various handlers.

Seems very weird that this is by design, can you explain rationale behind changing that behavior?

**Comment by ENikS** [comment]
The strategy, when resolving, looks for first occurrence of injection member with that name, once found it uses it and moves on. It never iterated through the rest of injected members to find out if there are more for the same method.

This optimization speeds up things considerably and justifies the decision.

**Pull request closed without merging**
